name: main-pr-merge

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    permissions: write-all
    # if the last commit message is a version bump, don't run
    # this action.
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Bump version

    steps:
      - uses: actions/checkout@v4
        # This is necessary for commitizen to see the previous commits,
        # which is what it uses to calculate the version bump.
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install commitizen
      - name: Get version before bump
        id: version_before
        run: |
          echo version_before was $(cz version --project)
          echo "version=$(cz version --project)" >> "$GITHUB_OUTPUT"
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version after bump
        id: version_after
        run: |
          echo version_after was $(cz version --project)
          echo "version=$(cz version --project)" >> "$GITHUB_OUTPUT"
      - name: Print Version
        run: echo "Bumped from version
          ${{ steps.version_before.outputs.version }} to
          ${{ steps.version_after.outputs.version }}"

    outputs:
      version_before: ${{ steps.version_before.outputs.version }}
      version_after: ${{ steps.version_after.outputs.version }}
      # todo: calculate bump size (major/minor/patch) and output it

