name: main-pr-merge

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  build_docs:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Mike
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "noreply@github.com"
          pip install mkdocs mike commitizen 
          VER=$(cz version --project) 
          mike deploy $VER latest --update-aliases 
          mike set-default latest --push

      - run: mike list

      - run: ls site

      - uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: site

